name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: test-billing-a.stridespace.com
      - name: Push result to Testspace server
        run: |
          testspace results.xml 
        if: always()
